[package]
name = "hoyo_gacha"
version = "1.0.0"
edition = "2021"
authors = ["lgou2w <lgou2w@hotmail.com>"]
description = "An unofficial tool for managing and analyzing your miHoYo gacha records"
homepage = "https://github.com/lgou2w/HoYo.Gacha#readme"
repository = "https://github.com/lgou2w/HoYo.Gacha"
readme = "../README.md"
license = "MIT OR Apache-2.0"
build = "src/build.rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
async-trait = "0.1.80"
backtrace = "0.3.73"
exponential-backoff = "1.2.0"
futures-util = "0.3.30"
num_enum = "0.7.2"
once_cell = "1.19.0"
paste = "1.0.15"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["preserve_order"] }
serde_repr = "0.1.19"
thiserror = "1.0.61"
time = { version = "0.3.36", features = ["formatting", "local-offset", "macros", "serde", "serde-human-readable"] }
tokio = { version = "1.38.0", features = ["macros", "rt", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "local-time"] }
url = "2.5.2"

[dependencies.sqlx]
version = "0.7.4"
default-features = false
features = [
  "runtime-tokio",
  "sqlite",
  "time",
  "tls-native-tls"
]

[dependencies.tauri]
version = "1.6.8"
features = [
  "devtools",
  "dialog-all",
  "os-all",
  "window-close",
  "window-maximize",
  "window-minimize",
  "window-unmaximize",
  "window-unminimize",
  "window-start-dragging"
]

[target.'cfg(windows)'.dependencies]
raw-window-handle = "0.5.2"
windows-version = "0.1.1"

[target.'cfg(windows)'.dependencies.windows]
version = "0.57.0"
features = [
  "Win32_Foundation",
  "Win32_Graphics",
  "Win32_Graphics_Dwm",
  "Win32_System_Com",
  "Win32_UI",
  "Win32_UI_Controls",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging"
]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
