[package]
name = "hoyo_gacha"
version = "1.0.0"
edition = "2021"
authors = ["lgou2w"]
description = "An unofficial tool for managing and analyzing your miHoYo gacha records"
homepage = "https://github.com/lgou2w/HoYo.Gacha#readme"
repository = "https://github.com/lgou2w/HoYo.Gacha"
readme = "../README.md"
license = "MIT OR Apache-2.0"
build = "build.rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
async-trait = "0.1.74"
futures-util = "0.3.29"
human-panic = "1.2.1"
num_enum = "0.7.1"
once_cell = "1.18.0"
paste = "1.0.14"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
serde_repr = "0.1.17"
thiserror = "1.0.50"
time = { version = "0.3.30", features = ["formatting", "local-offset", "macros", "serde", "serde-human-readable"] }
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.40"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "local-time"] }
url = "2.4.1"
window-shadows = "0.2.2"

[dependencies.sqlx]
version = "0.7.2"
default-features = false
features = [
  "runtime-tokio",
  "sqlite",
  "time",
  "tls-native-tls"
]

[dependencies.tauri]
version = "1.5.2"
features = [
  "os-all",
  "window-close",
  "window-maximize",
  "window-minimize",
  "window-unmaximize",
  "window-unminimize",
  "window-start-dragging"
]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
