[package]
name = "hoyo_gacha"
version = "1.0.0"
edition = "2021"
authors = ["lgou2w <lgou2w@hotmail.com>"]
description = "An unofficial tool for managing and analyzing your miHoYo gacha records"
homepage = "https://github.com/lgou2w/HoYo.Gacha#readme"
repository = "https://github.com/lgou2w/HoYo.Gacha"
readme = "../README.md"
license = "MIT OR Apache-2.0"
build = "build.rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-rc.12", default-features = false, features = ["config-toml"] }

[dependencies]
async-trait = "0.1.82"
backtrace = "0.3.74"
exponential-backoff = "2.0.0"
futures-util = "0.3.30"
num_enum = "0.7.3"
once_cell = "1.19.0"
os_info = "3.8.2"
paste = "1.0.15"
raw-window-handle = "0.6.2"
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["json"] }
rfd = { version = "0.14.1", default-features = false }
sha1 = "0.10.6"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["preserve_order"] }
serde_repr = "0.1.19"
sys-locale = "0.3.1"
tauri-plugin-shell = "2.0.0-rc.3"
tauri-plugin-clipboard-manager = "2.1.0-beta.7"
thiserror = "1.0.63"
time = { version = "0.3.36", features = ["formatting", "local-offset", "macros", "serde", "serde-human-readable"] }
tokio = { version = "1.40.0", features = ["macros", "rt", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "local-time"] }
url = "2.5.2"

[dependencies.sqlx]
version = "0.8.2"
default-features = false
features = [
  "runtime-tokio",
  "sqlite",
  "time",
  "tls-native-tls"
]

# https://github.com/tauri-apps/tauri/blob/dev/core/tauri/Cargo.toml
[dependencies.tauri]
version = "2.0.0-rc.15"
default-features = false
features = [
  "wry",
  "compression",
  "objc-exception",
  "devtools"
]

# Ensure that some dependencies are version-consistent with tauri to avoid type conflicts

[target.'cfg(windows)'.dependencies]
windows-registry = "0.2.0"
windows-version = "0.1.1"
webview2-com = "0.33.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.58.0"
features = [
  "Win32_Foundation",
  "Win32_Graphics",
  "Win32_Graphics_Dwm",
  "Win32_Security",
  "Win32_System_Com",
  "Win32_System_Console",
  "Win32_System_Threading",
  "Win32_UI",
  "Win32_UI_Controls",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging"
]

[dev-dependencies]
tempfile = "3.12.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
