name: 🐞 问题反馈
title: '[Bug] '
description: 通过这个议题反馈程序中的问题
labels: ['bug']

body:
  - type: textarea
    id: device-specification
    attributes:
      label: 设备规格
      description: |
        应用程序 - 设置 - 关于 - 设备规格
      placeholder: |
        操作系统 Windows 11 Professional
        系统版本 10.0.26100 x86_64
        Webview2 138.0.3351.109
        Tauri 2.7.0
        Git 提交 ac9e08baa99764c415db08ace89e2319d8488aed
        应用版本 v1.0.0-git-ac9e08b
    validations:
      required: true

  - type: dropdown
    id: user-category
    attributes:
      label: 问题分类
      description: 请设置一个你认为合适的分类，这将帮助我们快速定位问题。
      options:
        - 用户界面
        - 抽卡记录
        - 其它
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 发生了什么？
      description: |
        详细的描述问题发生的行为。如果你的问题涉及程序崩溃，请附上崩溃记录和日志文件。
        如果你无法找到该日志，请使用快捷键 `Win+R` 输入 `%USERPROFILE%\AppData\Local\com.lgou2w.hoyo.gacha.v1` 回车后可以找到 `Crashs` 和 `Logs` 文件夹。
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望的行为？
      description: 对你预期发生的情况的清晰描述。
    validations:
      required: false

  - type: checkboxes
    id: check-final
    attributes:
      label: 最后一步
      description: 回顾问题
      options:
        - label: 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。
          required: true
