name: Build

on:
  push:
    branches: [ main, v1 ]
  pull_request:
    branches: [ main, v1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            platform: windows-latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust environment
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Build app
        run: pnpm build

      - name: Build artifact
        run: pnpm build:artifact

      - name: Get short git commit sha
        id: short-sha
        shell: bash
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HoYo.Gacha-git-${{ steps.short-sha.outputs.short_sha }}
          path: |
            ${{ github.workspace }}/target/release/HoYo.Gacha.exe
